Dns v2
dchudik/octodns-selectel pull request #1
Opened 2023-12-12 20:20 UTC by dchudik

Added Dns V2

2023-12-12 21:18 UTC, dchudik commented on octodns_selectel/__init__.py
> +__version__ = __VERSION__ = '1.0.0'
На такую мажорную версию апнуть? Или это чересчур?

2023-12-12 21:19 UTC, dchudik commented on octodns_selectel/__init__.py
> +    # TODO: refactor it
Пока к сожалению не возникли идеи как разбить эту фунцию

2023-12-12 21:21 UTC, dchudik commented on octodns_selectel/__init__.py
> +        yield {
хотел уйти от yield в пользу return {}, но в строчке 126 используется for params in params_for(new): и не нашел идей лучше, чем просто оставить, так как если попробовать сделать return объекта, то там такого перебора не будет.

2023-12-12 21:22 UTC, dchudik commented on octodns_selectel/__init__.py
> +    # TODO: refactor it
Тоже с удовольствием бы отрефакторил, но не знаю на какие функции лучше разбить

2023-12-14 16:03 UTC, Archirk commented on octodns_selectel/__init__.py
> +__version__ = __VERSION__ = '1.0.0'
Пока оставь как есть. Ап версии мейнтенр проводит отдельным ПР\коммитом.

2023-12-14 16:08 UTC, Archirk commented on octodns_selectel/__init__.py
> +    # TODO: refactor it
Отвечаю к этому комменатрию и нижним, и верхнему - лучше подготовливать и оставлять в описании ПР.  
Или спрашивать в чате\личках при работе.
По умолчанию, в любом случае тот код который ты пушишь ты так или иначе готов мерджить.

Если ты сам понимаешь что качество кода хромает, но нет приоритета или понимания как сделать лучше - оставляй как есть. Если это будет критично для ревьювера - он отпишется. Если ты видишь что код плохой, то и ревьювер скорее всего это видит - нет нужды это отмечать отдельно.

2023-12-14 18:57 UTC, Archirk requested changes
Это комментарии по клиенту по провайдеру будут позже.

2023-12-14 18:57 UTC, Archirk commented on octodns_selectel/selectel_client.py
> +        super().__init__(message)
Инит данного класса абсолютно бесполезен и вместо него стоило бы ставить `pass` или `...`  
Я бы также предложил вынести исключения в отдельный файл `exceptions.py`

И сделать что-то вроде:
```python
class SelectelException(ProviderException):
   ...

class ProviderException(SelectelException):
   ...

class ApiException(SelectelException):
   ...
```  
Это уже заложит определенную организацию ошибок, пусть даже в таком небольшом проекте.

2023-12-14 18:57 UTC, Archirk commented on octodns_selectel/selectel_client.py
> +class SelectelClient(object):
Насколько мне известно наследование от `object`  - удел тех кто поддерживает python2.x
Мейнтенер более [не поддерживает](https://github.com/octodns/octodns/blob/main/CONTRIBUTING.md#how-to-contribute) python2(хотя это также понятно из-за использования f-строк) так что наследоваться от пустого объекта не надо.

так же что название файла что названия класса - избыточно - мы и так в репозитории октоднс-селектел, лучше дать более четкие названия.  
Это стилистика, но чем очевиднее, тем проще и быстрее будет проходить ревью мейнтенера.  
я бы предложил назвать `dns_client.py`, `DNSClient` соответсвенно

2023-12-14 18:57 UTC, Archirk commented on octodns_selectel/selectel_client.py
> +        path = '/zones'
Я бы предложил вынести эндпоинты на уровень неймспеса класса, чтобы было все в одном месте.  
Динамические я бы предложил определить через классовые методы:
```python
# --snip--
__zone_path = "/zones"
__zone_path_specifc = "/zones/{}"

@classmethod
def _signle_zone_path(cls, zone_uuid):
    return cls.__zone_path_specific.format(zone_uuid)
# --snip--
```
Дело вкуса, поэтому решай самостоятельно надо или нет

2023-12-14 18:57 UTC, Archirk commented on octodns_selectel/selectel_client.py
> +    PAGINATION_LIMIT = 50
Логически я бы просто указать что лимит - приватная константа:
 ```python
_PAGINATION_LIMIT = 50
```

2023-12-14 18:57 UTC, Archirk commented on octodns_selectel/selectel_client.py
> +        resp.raise_for_status()
Данная функция упадет с ошибок, если в ответе будет невалидный json. А такое может быть если ответы от нжинкса(как ранее было 401 или если 500)
Стоит лучше распарсить ответы в зависимости от кода(400,401,404, 409, >500) с использованим ApiException о котором речь была выше.
resp.raise_for_status() - полезный шорткат, но не информативный и его стоит исопльзовать для непредсказуемых ошибок, которые редко возникают.  

Также не уверен что при 404 надо возаращть пустой словарь. На это есть причины? или если мы рефакторим мы можем не тянуть за собой эту странность?

2023-12-14 18:57 UTC, Archirk commented on octodns_selectel/selectel_client.py
> +            return {}
По стандартам если ответ пустой то код 204.  
Наверное не стоит возвращать пустой словарь в зависимости от метода, а не от содержимого ответа и потому стоит удалить этот кусок.

2023-12-14 18:57 UTC, Archirk commented on octodns_selectel/selectel_client.py
> +        return result
можно сразу вернуть без записи в переменную, и нет смысла указать название парамс если он стоит на своем месте.
```python
return self._request(http.HTTPMethod.GET, path, dict(limit=self.PAGINATION_LIMIT, offset=offset))
```

2023-12-14 18:57 UTC, Archirk commented on octodns_selectel/selectel_client.py
> +    def __init__(self, library_version:str, token:str, *args, **kwargs):
либа внешняя, чем точнее мы пишем тем лучше.
Поэтому давай сразу навзовем не просто `token`, а `openstack_token`

2023-12-14 18:57 UTC, Archirk commented on octodns_selectel/selectel_client.py
> +        super().__init__(*args, **kwargs)
super() вызывает __init__ родительского класса. мы не от чего не наследумся, вызывать нам его нет смысла. поэтому нам также не нужны аргс и кваргс

2023-12-14 18:57 UTC, Archirk commented on octodns_selectel/selectel_client.py
> +        return result
Я бы предложил удалить функцию with offset и написать одну рекурсивную функцию которая бы собирала такой result.
Дело вкуса, решай сам.

2023-12-14 18:57 UTC, Archirk commented on octodns_selectel/selectel_client.py
> +    def zones(self):
функции стоит называть все таки действиям
в нашем случае
get_zone, list_zones, list_rrsets

2023-12-14 19:56 UTC, Archirk commented on octodns_selectel/__init__.py
> +    def _params_for_multiple(self, record):
Данный комментарий относиться ко всем `_params_for_...` и `_data_for_...`.  

_Дисклеймер: для упрощения работы я рекомендовал завезти тайп хинтинг, потому что работать без этого очень трудно, а пока будешь завозить покапаешься в коде. Его могу не принять на работать точно станет проще._


Если я верно понимаю record который передается, это инстанс собираемый на основе 1 единицы из файла конфигурации зоны.  Т.е. по сути это не рекорд сколько наш скорее наш родной rrset. Но есть нюансы в том что у нас 1 ррсет на одно имя, а вот record октодонс, кажется(требует проверки) может быть несколько на одно имя.

Таким образом я предлагаю сделать две функции за пределами класса: 
* `to_selectel_rrset(record)` - переводит в словарь который мы передим как тело запроса в клиент. Для форматирования content я рекомендую использовать [string.Template](https://docs.python.org/3/library/string.html#string.Template)
* `to_octodns_record(rrest)`
их будет очень легко и удобно юнит-тестировать.  

Затем мы будем использовать их вместо динамических вызов через getattr в apply и populate.

2023-12-14 20:30 UTC, Archirk requested changes

2023-12-14 20:30 UTC, Archirk commented on octodns_selectel/__init__.py
> +    def _params_for_multiple(self, record):
Данный комментарий относиться ко всем `_params_for_...` и `_data_for_...`.  

_Дисклеймер: для упрощения работы я рекомендовал завезти тайп хинтинг, потому что работать без этого очень трудно, а пока будешь завозить покапаешься в коде. Его могу не принять на работать точно станет проще._


Если я верно понимаю record который передается, это инстанс собираемый на основе 1 единицы из файла конфигурации зоны.  Т.е. по сути это не рекорд сколько наш скорее наш родной rrset. Но есть нюансы в том что у нас 1 ррсет на одно имя, а вот record октодонс, кажется(требует проверки) может быть несколько на одно имя.

Таким образом я предлагаю сделать две функции за пределами класса: 
* `to_selectel_rrset(record)` - переводит в словарь который мы передим как тело запроса в клиент. Для форматирования content я рекомендую использовать [string.Template](https://docs.python.org/3/library/string.html#string.Template)
* `to_octodns_record(rrest)`
их будет очень легко и удобно юнит-тестировать.  

Затем мы будем использовать их вместо динамических вызов через getattr в apply и populate.

2023-12-14 20:30 UTC, Archirk commented on octodns_selectel/__init__.py
> +            zone_id = self.create_zone(zone_name)['uuid']
Это плохое место для проверки и создания зоны - это будет происходить каждый раз при создании ррсета.
Стоит найти место где где это достаточно сделать один единтвенный раз.

2023-12-14 20:30 UTC, Archirk commented on octodns_selectel/__init__.py
> +        return zones_dict
Хоть я не уверен что данная функия как и то где храниться имеет смысл, но давайте дадим понятные названия и упростим:
```python
def group_existing_zones_by_name(self):
    return {zone['name']: zone for zone in self._client.zones()}
```

2023-12-14 20:30 UTC, Archirk commented on octodns_selectel/__init__.py
> +        return zone_rrsets
В отличие от зон, с хранение ррсетов и популейт я смысл не очень понял, можно объяснить?  
Больше всего смущает пробрасывание zone который пробрасывается из populate т.е. что то хз что

2023-12-14 20:30 UTC, Archirk commented on octodns_selectel/__init__.py
> +        fqdn = f'{rrset_name}.{zone_name}' if rrset_name else zone_name
имя ррсетов в апи уже включают в себя zone_name т.е. там всегда будет fqdn

2023-12-14 20:35 UTC, Archirk commented on octodns_selectel/selectel_client.py
> +    def zone_rrsets(self, zone_id):
Пиком юзабилити было бы добавить дата-классы да или просто классы соотвтествующие нашим ответам:
типа чтобы на выхожу в провайдере оперировали  Zone, RRSet и могли обращаться к ним не по словарю а все таки как аттрибутам. Это также упростило бы понимание нашего когда мейнтенром - он будет знать каким схемы возвращает наше апи.  
Но это на подумать и "бонусное"

2023-12-16 11:50 UTC, dchudik commented on octodns_selectel/selectel_client.py
> +class SelectelClient(object):
Убрал наследование от object

2023-12-16 11:52 UTC, dchudik commented on octodns_selectel/selectel_client.py
> +        path = '/zones'
Вынес отдельно эндпоинты в константы и сделал через классовые методы

2023-12-16 11:52 UTC, dchudik commented on octodns_selectel/selectel_client.py
> +    PAGINATION_LIMIT = 50
исправил

2023-12-16 11:52 UTC, dchudik commented on octodns_selectel/selectel_client.py
> +            return {}
Убрал этот кусок кода

2023-12-16 11:56 UTC, dchudik commented on octodns_selectel/selectel_client.py
> +        return result
Исправил. Использовал это при написании рекурсивной функции

2023-12-16 11:56 UTC, dchudik commented on octodns_selectel/selectel_client.py
> +        return result
Исправил. Использовал это при написании рекурсивной функции

2023-12-16 11:57 UTC, dchudik commented on octodns_selectel/selectel_client.py
> +    def __init__(self, library_version:str, token:str, *args, **kwargs):
Изменил название переменной

2023-12-16 11:58 UTC, dchudik commented on octodns_selectel/selectel_client.py
> +        super().__init__(*args, **kwargs)
Убрал *args, **kwargs и вызов конструктора родительского класса

2023-12-16 11:59 UTC, dchudik commented on octodns_selectel/selectel_client.py
> +    def zones(self):
исправил названия методов

2023-12-16 13:56 UTC, dchudik commented on octodns_selectel/selectel_client.py
> +        return result
Соглашусь, сделал рукурсивную функцию _request_all_entities

2023-12-16 14:59 UTC, dchudik commented on octodns_selectel/selectel_client.py
> +        resp.raise_for_status()
Исправил, добавил проверку ошибок. Убрал костыль с DELETE методом и resp.json() обернул в try

2023-12-16 15:02 UTC, dchudik commented on octodns_selectel/selectel_client.py
> +        super().__init__(message)
Сделал организацию ошибок и в методе _request у класса DNSClient их использую

2023-12-16 16:53 UTC, dchudik commented on octodns_selectel/__init__.py
> +            zone_id = self.create_zone(zone_name)['uuid']
Перенес эту проверку в функцию _aply

2023-12-16 16:58 UTC, dchudik commented on octodns_selectel/__init__.py
> +        fqdn = f'{rrset_name}.{zone_name}' if rrset_name else zone_name
Неверно написал. Там было не rrset_name, а record_name.  fqdn можно было получить из объекта изменений (change).
Исправил эту функцию и ушел от этого момента совсем.

2023-12-16 16:59 UTC, dchudik commented on octodns_selectel/__init__.py
> +        return zones_dict
Добавил данную функцию

2023-12-16 17:07 UTC, dchudik commented on octodns_selectel/__init__.py
> +    def _params_for_multiple(self, record):
`to_octodns_record(rrest)`
Скорее всего эта функция будет называться `to_octodns_records(rrest)`, так как из rrsetа мы конвертим в массив Recordов octodnsа.

С функцией `to_selectel_rrset(record)`, так как скорее всего функция будет `to_selectel_rrset(records)` и будет принмиать массив Recordов из октоднс. 

Могу попробовать реализовать такие функции

2023-12-17 13:25 UTC, Archirk requested changes
Так-с размер данного ревью становиться угнетающим.  
Предлагаю следующее:  
1) Довести все комментарии до состояния чтобы их можно было зарезолвить и резолвим их.
2) От твоей ветки `main` делаем ветку: `update_for_dnsv2_support`
3) Мерджим данный пул реквест не в `main` а в созданную ветку `update_for_dnsv2_support`  
4)  Далее ветвимся от ветки `update_for_dnsv2_support`  и делаем ПРы в нее.
5) В каждом ПР концентрируемся на более конкретных вещах, поскольку процесс идет не так гладко, чтобы все уместить в один ПР.   
На каких вещах конкретно концентрируемся - нужно спланировать заранее, лучше после созвона в понедельник.

2023-12-17 13:25 UTC, Archirk commented on octodns_selectel/dns_client.py
> +    def _request_all_entities(self, path, records=[], offset=0):
В питоне радикалы(и идешки) настоятельно рекомендуют не передавать в параметрах мутабельные переменные, коей является список. Следовало бы обойтись без него. Вот так, если я не ошибаюсь должно работать:
```python
def _request_all_entities(path, offset=0) -> list[int]:
    items = []
    resp = _request("GET", path, dict(limit=3, offset=offset))
    items.extend(resp["result"])
    if next_offset := resp["next_offset"]:
        items.extend(_request_all_entities(path, offset=next_offset))
    return items
```

2023-12-17 13:25 UTC, Archirk commented on octodns_selectel/dns_client.py
> +        return resp
Вкусовщина, но предлагаю быть компактнее.
Меньше кода - меньше простора для очепяток(здесь и соседних):
```python
def create_zone(self, name):
   return self._request("POST", self._zone_path, data=dict(name=name))
```
На твое усмотрение.

2023-12-17 13:25 UTC, Archirk commented on octodns_selectel/dns_client.py
> +    def _zone_path(cls):
Кажется, в этом методе нет смысла - ведь можно обратиться как классовому аттрибуту и так.  
Метод имеет смысл когда путь иметь динамические параметры.

2023-12-17 13:25 UTC, Archirk commented on octodns_selectel/dns_client.py
> +                resp.raise_for_status()
давайте просто все кейсы что не матчатся рейсить итернал еррор и принт уберем

2023-12-17 13:25 UTC, Archirk commented on octodns_selectel/dns_client.py
> +            raise SelectelException(e)
Я думаю достаточно в Value Error верунться SeletelException. 
Вообще я отмечу, что если пошло что-то не так: не стоит делать вид что все ок и все хоть что-то возвращать.  
+ в матчекесе 400 ты уже использоуешь r.json() а что если он там не валидный? Поэтому стоит эту конструкцию перенести перед матчкейсами.  
А также добавить под кейсы = 200 и 204(когда тело ответа пустое)

2023-12-17 13:25 UTC, Archirk commented on octodns_selectel/dns_client.py
> +                raise ApiException('Resource already created.')
409 - не всегда конфликт из-за того что что-то уже сущесвует.  
Поэтому можно также написать "Conflict:" и подставить поле еррор из ответа.

2023-12-17 13:25 UTC, Archirk commented on octodns_selectel/mappings.py
> +        case _ if "A" or "AAAA" or "NS":
я матч кейсами не пользовался, но конструкция одзназно страшно выглядит, кажется конструкция ниже корректнее и должна работать
```python
# --snip--
case "A" | "AAAA" | "NS":
# --snip--
```

2023-12-17 13:25 UTC, Archirk commented on octodns_selectel/mappings.py
> +                    lambda value: {'content': f'"{value}"', 'disabled': False},
поле disabled можно не указывать, оно всегда по умолсчанию будет фолс.

2023-12-17 13:25 UTC, Archirk commented on octodns_selectel/helpers.py
> +def require_root_domain(fqdn):
Я люблю раскидывать по файлам, но здесь мне кажется нужды нет  
Предлагаю указать что функция приватная (_) и более правлиьное имя: `_ensure_trailing_dot`

2023-12-17 13:25 UTC, Archirk commented on octodns_selectel/dns_client.py
> +                    f'Bad request. Description: {resp.json()["description"]}'
description - опциональное поле соответсвенно если его не будет будет ошибка.  
стоит написать безопаснее. вроде:
```python
f"Bad request: {resp.json().get("description", "Invalid payload")}"
```

2023-12-17 13:25 UTC, Archirk commented on octodns_selectel/__init__.py
> +            zone_id = self.create_zone(zone_name)['uuid']
вкусовщина,  но предлагаю избегать лишних элсов
```python
       if  not self._is_zone_already_created(zone_name):
            self.create_zone(zone_name)['uuid']
       zone_id = self._get_zone_id_by_name(zone_name)
```

2023-12-17 13:25 UTC, Archirk commented on octodns_selectel/__init__.py
> +                    raise SelectelProvider(
тут должен быть экспешион а не провайдер

2023-12-17 13:25 UTC, Archirk commented on octodns_selectel/__init__.py
> +        zone_id = ""
питон не го, объявлять незачем.

2023-12-17 13:25 UTC, Archirk commented on octodns_selectel/__init__.py
> +    def _get_zone_id_by_name(self, zone_name):
не стоит возвращать пусту строку. Все равно упадет дальше с ней.
Лучше пусть падает прямо тут в экспешион если не найдет.

2023-12-17 13:25 UTC, Archirk commented on octodns_selectel/__init__.py
> +            return ""
тоже давайте сразу напрямую получать rrsets[zone_name]  что если что0то пойдет не так сразу было вдино что тут проблема. и чуть ниже в функции тоже самое

2023-12-17 13:25 UTC, Archirk commented on octodns_selectel/__init__.py
> +            self._zone_rrsets[zone.name] = zone_rrsets
если внести изменения по тому чтобы не возарщался пустые строки как айди зоны, тут соотвтсвенно можно будет упростить.

2023-12-17 13:25 UTC, Archirk commented on octodns_selectel/__init__.py
> +        except HTTPError:
А вот здесь стоит ловить ApiException

2023-12-17 13:25 UTC, Archirk commented on octodns_selectel/__init__.py
> +                        f'Method {action.lower()} not implemented'
вкусовщина, следующий текст мне кажется точнее:
` Unexpected change type: {action}`  
кстати .lower() наверное имеет смыслать сразу при объявлении action сделать раз уж он исопльзуется два раза(да и логичнее)

2023-12-17 13:35 UTC, Archirk commented on octodns_selectel/selectel_client.py
> +    def zone_rrsets(self, zone_id):
пока не будем об этом думать. резолвлю

2023-12-17 21:08 UTC, dchudik commented on octodns_selectel/__init__.py
> +                        f'Method {action.lower()} not implemented'
Исправил комментарий. Сделал .lower() при объявлении action

2023-12-17 21:08 UTC, dchudik commented on octodns_selectel/__init__.py
> +        except HTTPError:
отловил ApiException

2023-12-17 21:09 UTC, dchudik commented on octodns_selectel/__init__.py
> +            self._zone_rrsets[zone.name] = zone_rrsets
Убрал возврат пустых строк. Сделал так чтобы, если зона не найдена, то падало с SelectelException

2023-12-17 21:11 UTC, dchudik commented on octodns_selectel/dns_client.py
> +    def _request_all_entities(self, path, records=[], offset=0):
Добавил данную фунцию поправив limit, и добавив self

2023-12-17 21:11 UTC, dchudik commented on octodns_selectel/dns_client.py
> +    def _request_all_entities(self, path, records=[], offset=0):
Добавил данную фунцию поправив limit, и добавив self

2023-12-17 21:14 UTC, dchudik commented on octodns_selectel/dns_client.py
> +        return resp
Да, выглядит сильно проще. Поправил ещё так же функцию list_zones.

2023-12-17 21:15 UTC, dchudik commented on octodns_selectel/dns_client.py
> +    def _zone_path(cls):
Оставил только переменную _zone_path со значением "/zones"

2023-12-17 21:18 UTC, dchudik commented on octodns_selectel/__init__.py
> +            return ""
Подправил функцию. Не смог сделать выброс SelectelException как в функции _get_zone_id_by_name, но она всё равно упадёт с ошибкой, если что-то не так.

2023-12-17 21:21 UTC, dchudik commented on octodns_selectel/mappings.py
> +        case _ if "A" or "AAAA" or "NS":
Исправил

2023-12-17 21:22 UTC, dchudik commented on octodns_selectel/mappings.py
> +        case _ if "A" or "AAAA" or "NS":
Исправил

2023-12-17 21:24 UTC, dchudik commented on octodns_selectel/mappings.py
> +                    lambda value: {'content': f'"{value}"', 'disabled': False},
Убрал

2023-12-17 21:27 UTC, dchudik commented on octodns_selectel/helpers.py
> +def require_root_domain(fqdn):
Название функции исправил. 
В данный момент расскинул, так как функция была в init файле, а ещё понадобилась в mappingах. Чтобы не было циклической зависимости, я вынес в отдельный файл.

2023-12-17 21:28 UTC, dchudik commented on octodns_selectel/__init__.py
> +    def _get_zone_id_by_name(self, zone_name):
Сделал. Удалось выкидывать SelectelException.

2023-12-17 21:29 UTC, dchudik commented on octodns_selectel/__init__.py
> +        zone_id = ""
Убрал

2023-12-17 22:09 UTC, dchudik commented on octodns_selectel/dns_client.py
> +                    f'Bad request. Description: {resp.json()["description"]}'
Исправил, сделал безопаснее

2023-12-17 22:10 UTC, dchudik commented on octodns_selectel/__init__.py
> +            zone_id = self.create_zone(zone_name)['uuid']
убрал лишнюю проверку

2023-12-17 22:11 UTC, dchudik commented on octodns_selectel/__init__.py
> +                    raise SelectelProvider(
Исправил

2023-12-17 22:13 UTC, dchudik commented on octodns_selectel/__init__.py
> +        yield {
удалось от этого уйти

2023-12-17 22:14 UTC, dchudik commented on octodns_selectel/__init__.py
> +__version__ = __VERSION__ = '1.0.0'
Оставил как есть

2023-12-18 06:42 UTC, dchudik commented on octodns_selectel/dns_client.py
> +                resp.raise_for_status()
Убрал `print`. Сделал 500 и всё что не матчится `raise ApiException('Internal server error.')`

2023-12-18 06:44 UTC, dchudik commented on octodns_selectel/dns_client.py
> +            raise SelectelException(e)
Перед матчем сделал словарь и безопасное получение значение в него из `resp.json()`.
```
try:
            resp_json = resp.json()
        except Exception:
            resp_json = {}
```

В матче обработал успешные кейсы (200,201,204). Сделал `return resp_json`

2023-12-18 06:44 UTC, dchudik commented on octodns_selectel/dns_client.py
> +            raise SelectelException(e)
Перед матчем сделал словарь и безопасное получение значение в него из `resp.json()`.
```
try:
            resp_json = resp.json()
        except Exception:
            resp_json = {}
```

В матче обработал успешные кейсы (200,201,204). Сделал `return resp_json`

2023-12-18 06:45 UTC, dchudik commented on octodns_selectel/dns_client.py
> +                raise ApiException('Resource already created.')
Сделал безопасно через `.get()`

2023-12-18 06:45 UTC, dchudik commented on octodns_selectel/dns_client.py
> +                raise ApiException('Resource already created.')
Сделал безопасно через `.get()`

2023-12-18 07:00 UTC, dchudik commented on octodns_selectel/__init__.py
> +        return zone_rrsets
Это для снапшота состояния всех доменов и ррсетов в системе на момент запуска. Делается, для того, чтобы сходить в апишку один раз и закешировать данные и можно было работать с данными как словарь

2023-12-18 14:05 UTC, Archirk approved these changes

2023-12-18 14:30 UTC, merged