Fix mappings. Added tests for mappings with 100% coverage.
dchudik/octodns-selectel pull request #3
Opened 2023-12-21 07:34 UTC by dchudik

2023-12-21 12:40 UTC, Archirk requested changes

2023-12-21 12:40 UTC, Archirk commented on tests/test_selectel_mappings.py
> +    _invalid_type_record = ARecord(
Я смею назвать неприличным объявлять аттрибуты в середине определния класса.  
Такое надо делать в начале.  и возможно даже за пределами класса.  
Но я предлагаю и вовсе просто сузить скоуп их исопльзования до одного теста. Пример выше

2023-12-21 12:40 UTC, Archirk commented on tests/test_selectel_mappings.py
> +    zone = Zone("test-octodns.ru.", [])
здесь не принципиально, но представим что зона переиспользуется в каждом тесте. и модифициурется в каждом тесте. Её содержимое становится непредсказуемым.  Поэтому такие переменные логично поместить в setUp
```python
    def setUp(self):
        self.zone = Zone("test-octodns.ru.", [])
```

2023-12-21 12:40 UTC, Archirk commented on tests/test_selectel_mappings.py
> +    def test_to_octodns_record_a(self):
Далее речь не о кокнретной функции а обо всех но напримере тестирвания парсера для А.  

Тестирование парсинга а записи мне кажется минимальным. Лично я любитель покрывать с лихвой.
Поэтому нужны более понятные конструкции чтобы уместить много тест кейсов.  
Я бы предложил такую:

```python
# --snip--
# Над классом определим структуру, в ней мы будем хранить 2 инстанса данных которые представляют друг друг в разных интерфйесах. Тут использован нейм тупл но можно хоть дата класс хоть словарь, хоть список.
TestPair = collections.namedtuple("TestPair", ["record", "rrset"])
# --snip--
# Эта функция, по сути шорт кат, которые проверяет что оба объекта друг в друга парсятся. Аналогично можно продумать функцию если нужно ассертит некорретные данные.
    def _assert_mapping(self, test_pairs):
        for tc in test_pairs:
            with self.subTest():
                rrset_from_record = to_selectel_rrset(tc.record)
                self.assertEqual(rrset_from_record.get("name"), tc.rrset["name"])
                self.assertEqual(rrset_from_record.get("type"), tc.rrset["type"])
                self.assertEqual(rrset_from_record.get("ttl"), tc.rrset["ttl"])
                self.assertEqual(rrset_from_record.get("records"), tc.rrset["records"])
                
                record_data_from_rrset = to_octodns_record(tc.rrset)
                self.assertEqual(record_data_from_rrset.get("type"), tc.record._type)
                self.assertEqual(record_data_from_rrset.get("ttl"), tc.record.ttl)
                self.assertEqual(record_data_from_rrset.get("values"), tc.record.values)

# Сам тест в таком случае это просто набор тест-кейсов, что идеально
    def test_mapping_record_a(self):
        ipv4_list = ["10.20.30.40", "50.60.70.80"]
        test_pairs = (
            TestPair(
                ARecord(self.zone, "a", dict(ttl=self.ttl, value=ipv4_list[0])),
                dict(name=f"a.{self.zone.name}", ttl=self.ttl, type="A", records=[dict(content=ipv4_list[0])])
                ),
            TestPair(
                ARecord(self.zone, "a", dict(ttl=self.ttl, values=ipv4_list)),
                dict(name=f"a.{self.zone.name}", ttl=self.ttl, type="A", records=[dict(content=ipv4_list[0]), dict(content=ipv4_list[1])])
                ),
            TestPair(
                ARecord(self.zone, "", dict(ttl=self.ttl, values=ipv4_list)),
                dict(name=self.zone.name, ttl=self.ttl, type="A", records=[dict(content=ipv4_list[0]), dict(content=ipv4_list[1])])
                ),
        )
        self._assert_mapping(test_pairs)
```

2023-12-21 12:40 UTC, Archirk commented on tests/test_selectel_mappings.py
> +        record = to_octodns_record(self._a_rrset)
Кстати меня и ранее мучали вопросы, но на тестах я прочувтсвла и запутался.
что все таки эта функция парсит не в Record класс, а просто словарь который туда пробрасывается.  
Тут надо подумать как поступать в зависимости от другого кода: таки парсить прямо в Record или просто переменовать функцию в to_octodns_record_data

2023-12-21 12:54 UTC, Archirk commented on tests/test_selectel_mappings.py
> +        str(ipaddress.IPv6Address("4ad4:a6c4:f856:08be:5a5f:7f16:cc3a:fab9")),
Странная конструкция, наверное дл само проверки что айпив6 адрес верный.
я думаю можно проверить через свой терминал в а тесте просто оставить переменную строку без этих преобразований

2023-12-21 17:49 UTC, dchudik commented on tests/test_selectel_mappings.py
> +        str(ipaddress.IPv6Address("4ad4:a6c4:f856:08be:5a5f:7f16:cc3a:fab9")),
Я пробовал изначально строку, но получилось так, что если в один из октетов айпишника начинается с нуля, то 0 обрезается в классе AaaaRecord.
И получается, тест падает, так как списки отличаются значениями.
Ниже пример упавшего теста.
```
E       AssertionError: Lists differ: ['4ad4:a6c4:f856:8be:5a5f:7f16:cc3a:fab9', 'da78:f69b:8e5a[22 chars]eab'] != ['4ad4:a6c4:f856:08be:5a5f:7f16:cc3a:fab9', 'da78:f69b:8e5[23 chars]eab']
E       
E       First differing element 0:
E       '4ad4:a6c4:f856:8be:5a5f:7f16:cc3a:fab9'
E       '4ad4:a6c4:f856:08be:5a5f:7f16:cc3a:fab9'
E       
E       - ['4ad4:a6c4:f856:8be:5a5f:7f16:cc3a:fab9',
E       + ['4ad4:a6c4:f856:08be:5a5f:7f16:cc3a:fab9',
E       ?                  +
E       
E          'da78:f69b:8e5a:6221:d0c9:64b8:c6c0:2eab'] : Values from rrset must equals values in record
```

2023-12-21 19:25 UTC, Archirk commented on tests/test_selectel_mappings.py
> +        str(ipaddress.IPv6Address("4ad4:a6c4:f856:08be:5a5f:7f16:cc3a:fab9")),
а понятно
Чисто ради красоты я бы просто использовал айпи адреса без нуля в таком случае.
Но это вкусовщина, так что сам решай по ситуации.

2023-12-22 11:10 UTC, dchudik commented on tests/test_selectel_mappings.py
> +    _invalid_type_record = ARecord(
Оставил две переменные(ttl, zone) в функции setUp. Остальные сделал на уровне скоупа

2023-12-22 11:11 UTC, dchudik commented on tests/test_selectel_mappings.py
> +    zone = Zone("test-octodns.ru.", [])
ttl и zone вынес в данную функцию

2023-12-22 11:12 UTC, dchudik commented on tests/test_selectel_mappings.py
> +    def test_to_octodns_record_a(self):
Все тесты исправил по этому образцу

2023-12-22 11:13 UTC, dchudik commented on tests/test_selectel_mappings.py
> +        record = to_octodns_record(self._a_rrset)
Переименовал функцию маппинга в to_octodns_record_data

2023-12-22 12:01 UTC, dchudik commented on tests/test_selectel_mappings.py
> +        str(ipaddress.IPv6Address("4ad4:a6c4:f856:08be:5a5f:7f16:cc3a:fab9")),
Да, убрал 0 в первом октете и оставил значения как строки

2023-12-22 12:22 UTC, Archirk approved these changes
Хорошо

2023-12-22 12:31 UTC, merged