Edit some error messages. Added tests for DNSCLient
dchudik/octodns-selectel pull request #4
Opened 2023-12-22 15:55 UTC by dchudik

2023-12-25 11:58 UTC, Archirk requested changes
Все хорошо. Все замечамения стилистические.
Можешь ирспавтьи и пингануть меня. Я эппрувно.
Напомню, что по хорошему, надо сделать тесты для функций _apply и populate для провайдера.
Вероятно, можно просто поправить адреса вызовов существых тестов провайдера и этого должно быть достатотчно, потому что там прямо-верхнеровневый тесты и поэтому от того чтобы мы поменяли содержимое - тест не должен ломаться. Будет не получаться - пиши

2023-12-25 11:58 UTC, Archirk commented on tests/test_selectel_dns_client.py
> +    openstack_token = "oasdjoinfhusaiuhsduhsuidahuishiuhsdiu"
Я бы сказал что это "не профессионально". Если для теста не имеет значения содержимое переменной, то лучше в неё помещать содержимое вроде "some-openstask-token".

2023-12-25 11:58 UTC, Archirk commented on tests/test_selectel_dns_client.py
> +    API_URL = 'https://api.selectel.ru/domains/v2'
Здесь так же, лучше поместить что-то вроде https://dns-api.selectel чтобы дать сразу при просмоторе что для теста нерелавнтен реальный адрес.

2023-12-25 11:58 UTC, Archirk commented on tests/test_selectel_dns_client.py
> +        """
Кажется это оверкил. Мы не парсим плаин текст и достаточно просто того что при моке мы посмотрим только на код

2023-12-25 11:58 UTC, Archirk commented on tests/test_selectel_dns_client.py
>          )
Кажется данный набор тестов бессмысленен.
Если у тебя в тестах покрыты все вызовы по эндпоинтам - это будет означать что они войдут в ковередж.  
Ковередж, смотрим ни то сколько у тебя тестов на функции, а но то что зайдествутеся лв тестах у тебя весь код и ветветления.
Т.е. вызов данных функций в других функциях уже должен помещать их под ковередж. Попробуй закомментить и првоерить.

2023-12-25 11:58 UTC, Archirk commented on tests/test_selectel_dns_client.py
> +        )
Не могу понять смысл теста.
Могу представить если бы мы рейсили еррор когда токен не передали(но это надо было бы делать при инициации инстанса днс-клиент)
Кажется он лишний и на ковередж не должен влиять.

2023-12-25 11:58 UTC, Archirk commented on tests/test_selectel_dns_client.py
> +        )
Кажется по логике вещей следовало бы поместить данные асерт внутрь контекстного менеджера with.  Тут и в других местах.

2023-12-25 11:58 UTC, Archirk commented on tests/test_selectel_dns_client.py
> +        print("Msg: " + str(api_exception.exception))
принт забыл убрать

2023-12-25 11:58 UTC, Archirk commented on tests/test_selectel_dns_client.py
> +            self.dns_client._request(
Почему именно делать тест через вызов публичного метода?
По-моему вполне резонно сразу использовать подходящий публичный. Здесь и в других местах.

2023-12-27 15:26 UTC, dchudik commented on tests/test_selectel_dns_client.py
> +    openstack_token = "oasdjoinfhusaiuhsduhsuidahuishiuhsdiu"
Исправил

2023-12-27 15:29 UTC, dchudik commented on tests/test_selectel_dns_client.py
> +    API_URL = 'https://api.selectel.ru/domains/v2'
Попробовал, но вернул обратно к значению 'https://api.selectel.ru/domains/v2'.
Данный URL зашит прямо в классе. И поэтому мокаю урл, который вызывается в классе.
Оставить такой урл? Или сделать возможность задавать урл через конструктор класса?

2023-12-27 15:32 UTC, dchudik commented on tests/test_selectel_dns_client.py
> +        """
Решил сделать один тест с телом, которое не в формате json. Чтобы узнать, что resp.json() у нас отрабатывает в трай кетч и при рефакторинге в следующий раз его не вынесли.
Если помнишь странную конструкцию if method == 'DELETE',  то это было сделано для того чтобы не крашилась функция при возврате пустого значения в body ответа

2023-12-27 15:33 UTC, dchudik commented on tests/test_selectel_dns_client.py
>          )
Убрал данные тесты, кавередж сохранился

2023-12-27 15:33 UTC, dchudik commented on tests/test_selectel_dns_client.py
> +        )
Убрал тест

2023-12-27 15:33 UTC, dchudik commented on tests/test_selectel_dns_client.py
> +        print("Msg: " + str(api_exception.exception))
Убрал

2023-12-27 15:40 UTC, dchudik commented
Исправил часть замечаний

2023-12-27 15:42 UTC, dchudik commented on tests/test_selectel_dns_client.py
> +            self.dns_client._request(
Решил не вызывать функции, которые служат как абстракции.
Исправлю тогда на вызов list_zones

2023-12-27 15:43 UTC, dchudik commented on tests/test_selectel_dns_client.py
> +        )
Тоже так думал. Как выяснил, если разместить данный ассерт в блоке with, то ассерт не отработает вообще
![Screenshot from 2023-12-27 18-21-26](https://github.com/dchudik/octodns-selectel/assets/30375483/a0bc0d4c-fe41-45e1-8911-aca7727dfdb0)
![Screenshot from 2023-12-27 18-21-37](https://github.com/dchudik/octodns-selectel/assets/30375483/4bcd41b8-d24c-4927-a201-65585c710125)

2023-12-27 15:54 UTC, Archirk commented on tests/test_selectel_dns_client.py
> +    API_URL = 'https://api.selectel.ru/domains/v2'
Тогда наверное имеет смысл обращаться к аттрибуту клиента
self.dns_client.API_URL при моках хттп?

2023-12-27 16:12 UTC, dchudik commented on tests/test_selectel_dns_client.py
> +    API_URL = 'https://api.selectel.ru/domains/v2'
Исправил

2023-12-27 16:54 UTC, dchudik commented on tests/test_selectel_dns_client.py
> +            self.dns_client._request(
Исправил на вызов разных публичных функций. Но название тестов не менял, думаю смысл не сильно поменяется. И убрал одну функцию со статикметодом, которая не использовалась в публичных методах (чтобы кавередж остался 100).

2023-12-28 15:06 UTC, Archirk commented on tests/test_selectel_dns_client.py
> +        """
Поскольку мы не парсим плеин текст, для нас нет разницы пустое тело или есть там хтмл - .json() зарейсит исключение в обоих случаях.  
Но если хочешь - можно оставить.
Резолвлю

2023-12-28 15:06 UTC, Archirk approved these changes
Ок. Можно двигаться дальше

2023-12-28 23:31 UTC, merged